ai:
  provider: openai
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 100
  api_key: "" # Replace with your OpenAI API key or set COMMY_API_KEY env variable
commit_style: conventional # Options: conventional, simple
diff_truncation_limit: 4000 # Characters
